import bcrypt from "bcryptjs";
import {estimatePrice,materialRates,matchScore} from "./domain.js";
const now=()=>new Date().toISOString();
const meta=(source="DEMO_SEED")=>({createdAt:now(),updatedAt:now(),source,validationStatus:"DEMO_VALIDATED",seededDemoData:true});
const taxonomy:Record<string,string[]>={CRT:["Television tube","Monitor tube"],LCD:["Laptop display","Television display","Mobile display"],PCB:["Low grade board","Medium grade board","High grade board"],Cable:["Copper cable","Mixed wire","Data cable"],Battery:["Lithium-ion","Lead-acid","Nickel-metal hydride"],Motor:["Small motor","Compressor motor","Fan motor"],"Magnet assembly":["Speaker magnet","Hard-drive magnet","Mixed magnet"],"Mixed plastics":["ABS","HIPS","Mixed casing"]};
const names:Record<string,{hi:string;mr:string}>={CRT:{hi:"सीआरटी",mr:"सीआरटी"},LCD:{hi:"एलसीडी",mr:"एलसीडी"},PCB:{hi:"पीसीबी",mr:"पीसीबी"},Cable:{hi:"केबल",mr:"केबल"},Battery:{hi:"बैटरी",mr:"बॅटरी"},Motor:{hi:"मोटर",mr:"मोटर"},"Magnet assembly":{hi:"चुंबक असेंबली",mr:"चुंबक असेंब्ली"},"Mixed plastics":{hi:"मिश्रित प्लास्टिक",mr:"मिश्र प्लास्टिक"}};
export const materials=Object.entries(taxonomy).flatMap(([category,subs])=>subs.map((subcategory,index)=>({id:`mat-${category.toLowerCase().replace(/[^a-z]+/g,"-")}-${index+1}`,category,subcategory,name:category,hi:names[category].hi,mr:names[category].mr,safetyLevel:["Battery","CRT"].includes(category)?"HIGH":"NORMAL",description:`${subcategory} e-waste`,rate:materialRates[category]||70,active:true,...meta()})));
export const priceRecords=materials.flatMap((material,mi)=>[0,7,14,21,30].map((daysAgo,hi)=>{const base=material.rate+mi*2-hi*3;return{id:`price-${mi+1}-${hi+1}`,materialId:material.id,category:material.category,subcategory:material.subcategory,location:"Pune, Maharashtra",effectiveDate:new Date(Date.now()-daysAgo*86400000).toISOString(),minRate:Math.round(base*.88),maxRate:Math.round(base*1.12),unit:"kg",offeredBy:"Demo recycler price survey",...meta("DEMO_PRICE_SURVEY")};}));
export const recyclers=Array.from({length:8},(_,i)=>{const categories=i%2?["PCB","Cable","Motor","Magnet assembly"]:["Battery","LCD","CRT","Mixed plastics"];const r={id:`r${i+1}`,name:["GreenCycle Pune","EcoLoop Recyclers","Bharat E-Recovery","Sahyadri Circular","Urban Mine Works","CleanTech Metals","ReNew E-Waste","Prithvi Recovery"][i],facilityLocation:`${["Hadapsar","Bhosari","Chakan","Kondhwa","Pimpri","Talegaon","Ranjangaon","Wagholi"][i]}, Pune`,location:"Pune, Maharashtra",distance:2.4+i*1.35,authorized:i!==7,authorizationNumber:`DEMO-MPCB-EW-${2100+i}`,authorizationStatus:i===7?"PENDING_VERIFICATION":"AUTHORIZED",status:i===7?"PENDING_VERIFICATION":"AUTHORIZED",verificationLabel:"Prototype record — registry verification not connected",contact:`020-4000${1000+i}`,materials:categories,materialsAccepted:categories,serviceArea:["Pune","Pimpri-Chinchwad"],offeredRates:categories.map(category=>({category,rate:(materialRates[category]||70)+8+i*2})),offer:420+i*4,pickup:i!==6,pickupAvailable:i!==6,reliability:97-i,...meta("DEMO_RECYCLER_DIRECTORY")};return{...r,matchScore:matchScore({distance:r.distance,price:r.offer,maxPrice:456,authorized:r.authorized,pickup:r.pickup,reliability:r.reliability})};}).sort((a,b)=>b.matchScore-a.matchScore);
export let users:any[]=[{id:"u-customer",name:"Priya Sharma",email:"user@kabadi.local",phone:"5555555555",role:"CUSTOMER",preferredLanguage:"en",status:"APPROVED",...meta()},{id:"u-collector",name:"Ramesh Kumar",email:"collector@kabadi.local",phone:"6666666666",role:"COLLECTOR",preferredLanguage:"hi",generalOperatingLocation:"Pune",status:"APPROVED",...meta()},{id:"u-aggregator",name:"Shakti Aggregator",email:"aggregator@kabadi.local",phone:"7777777777",role:"AGGREGATOR",preferredLanguage:"mr",generalOperatingLocation:"Pimpri",status:"APPROVED",...meta()},{id:"u-recycler",name:"GreenCycle Pune",email:"recycler@kabadi.local",phone:"9876543211",role:"RECYCLER",preferredLanguage:"en",status:"APPROVED",recyclerId:"r1",...meta()},{id:"u-admin",name:"Asha Admin",email:"admin@kabadi.local",phone:"9876543212",role:"ADMIN",preferredLanguage:"en",status:"APPROVED",...meta()},{id:"u-data",name:"Data Operator",email:"data@kabadi.local",phone:"9876543213",role:"DATA_OPERATOR",preferredLanguage:"en",status:"APPROVED",...meta()}];
export const safetyContent:any[]=[{id:"safe-battery",material:"Battery",title:{en:"Handle batteries carefully",hi:"बैटरी सावधानी से संभालें",mr:"बॅटरी काळजीपूर्वक हाताळा"},body:{en:"Keep damaged batteries separate, dry and away from heat. Do not open or burn them.",hi:"क्षतिग्रस्त बैटरी अलग, सूखी और गर्मी से दूर रखें। इन्हें खोलें या जलाएँ नहीं।",mr:"खराब बॅटरी वेगळी, कोरडी आणि उष्णतेपासून दूर ठेवा. ती उघडू किंवा जाळू नका."},active:true,...meta("SAFETY_DEMO_CONTENT")}];
export let lots:any[]=[];export let quotes:any[]=[];export let payments:any[]=[];export let handovers:any[]=[];export let anomalies:any[]=[];export let audits:any[]=[];export let notifications:any[]=[];export let orders:any[]=[];export let marketplaceOffers:any[]=[];export let coupons:any[]=[];export let businessConfig={commissionPercent:0,deliveryCharge:0,freeDeliveryAbove:0};export const synced=new Set<string>();
export function setBusinessConfig(value:any){businessConfig=value;return businessConfig;}
export async function resetData(){lots=Array.from({length:36},(_,i)=>{const material=materials[i%materials.length];const weight=+(3+(i%12)*1.5).toFixed(1);const p=estimatePrice(material.category,weight);const statuses=["CREATED","MATCHED","REQUESTED","ACCEPTED","SCHEDULED","HANDED_OVER","VERIFIED","COMPLETED"];return{id:`lot-${i+1}`,lotId:`KC-20260923-${String(i+101).padStart(6,"0")}`,collectorId:i%5?"u-collector":"u-aggregator",materialCategory:material.category,materialSubcategory:material.subcategory,description:material.description,photoUrl:"",approxWeight:weight,condition:"USED",sourceType:"HOUSEHOLD_COLLECTION",location:{label:"Pune, Maharashtra",latitude:18.5204,longitude:73.8567,accuracy:25,capturedAt:now()},estimatedValue:p.average*weight,priceRange:{low:p.totalLow,high:p.totalHigh},status:statuses[i%statuses.length],syncStatus:"SYNCED",recyclerId:i%3?"r1":null,...meta()};});quotes=[];handovers=[];payments=lots.filter(x=>x.status==="COMPLETED").map((x,i)=>({id:`pay-${i}`,lotId:x.lotId,amount:Math.round(x.estimatedValue),method:i%2?"UPI":"CASH",status:"PAID",transactionReference:`DEMO-PAY-${i+1}`,paidAt:x.createdAt,...meta()}));anomalies=[];audits=[];notifications=[];orders=[];marketplaceOffers=[];coupons=[];businessConfig={commissionPercent:0,deliveryCharge:0,freeDeliveryAbove:0};synced.clear();}
export const passwordHash=await bcrypt.hash("Demo123!",10);await resetData();
export function snapshotData(){return{users,lots,quotes,payments,handovers,anomalies,audits,notifications,orders,marketplaceOffers,coupons,businessConfig,synced:[...synced]};}
export function hydrateData(state:any){if(!state||typeof state!=="object")return;users=Array.isArray(state.users)?state.users:users;if(!users.some(u=>u.id==="u-customer"))users.push({id:"u-customer",name:"Priya Sharma",email:"user@kabadi.local",phone:"5555555555",role:"CUSTOMER",preferredLanguage:"en",status:"APPROVED",...meta()});lots=Array.isArray(state.lots)?state.lots:lots;quotes=Array.isArray(state.quotes)?state.quotes:quotes;payments=Array.isArray(state.payments)?state.payments:payments;handovers=Array.isArray(state.handovers)?state.handovers:handovers;anomalies=Array.isArray(state.anomalies)?state.anomalies:anomalies;audits=Array.isArray(state.audits)?state.audits:audits;notifications=Array.isArray(state.notifications)?state.notifications:notifications;orders=Array.isArray(state.orders)?state.orders:[];marketplaceOffers=Array.isArray(state.marketplaceOffers)?state.marketplaceOffers:[];synced.clear();for(const id of state.synced||[])synced.add(String(id));}
