import i18n from "./i18n";

const mr: Record<string, string> = {
  Home: "मुख्यपृष्ठ",
  Lots: "लॉट",
  Prices: "किंमती",
  Recyclers: "रिसायकलर",
  Safety: "सुरक्षा",
  Earnings: "कमाई",
  Dashboard: "डॅशबोर्ड",
  "Incoming lots": "येणारे लॉट",
  Operations: "कामकाज",
  Analytics: "विश्लेषण",
  Intelligence: "नेटवर्क माहिती",
  Anomalies: "विसंगती",
  Datasets: "डेटासेट",
  Business: "व्यवसाय",
  "Audit log": "ऑडिट नोंद",
  "DEMO MODE": "डेमो मोड",
  "SMART E-WASTE NETWORK": "स्मार्ट ई-कचरा नेटवर्क",
  "COLLECTOR workspace": "संकलक कार्यक्षेत्र",
  "RECYCLER workspace": "रिसायकलर कार्यक्षेत्र",
  "ADMIN workspace": "प्रशासक कार्यक्षेत्र",
  "Collector home": "संकलक मुख्यपृष्ठ",
  "This month": "या महिन्यात",
  "Formal e-waste": "औपचारिक ई-कचरा",
  "Safely routed": "सुरक्षितपणे पाठवले",
  "Active lots": "सक्रिय लॉट",
  "Across the network": "संपूर्ण नेटवर्कमध्ये",
  "Trusted recyclers": "विश्वसनीय रिसायकलर",
  "Demo-verified": "डेमो-सत्यापित",
  "What do you want to do?": "तुम्हाला काय करायचे आहे?",
  "Why KABADI+?": "KABADI+ का?",
  "Safety reminder": "सुरक्षा सूचना",
  "Open safety centre": "सुरक्षा केंद्र उघडा",
  "AI-assisted identification": "AI-सहाय्यित ओळख",
  "Scan scrap": "स्क्रॅप स्कॅन करा",
  "AI DEMO MODEL": "AI डेमो मॉडेल",
  "Take or choose a scrap photo": "स्क्रॅपचा फोटो काढा किंवा निवडा",
  "Open camera": "कॅमेरा उघडा",
  "Analyze material": "साहित्य तपासा",
  "AI result will appear here": "AI निकाल येथे दिसेल",
  "AI result": "AI निकाल",
  Confidence: "विश्वास पातळी",
  Condition: "स्थिती",
  "Estimated weight": "अंदाजे वजन",
  "Estimated fair value": "अंदाजे योग्य किंमत",
  "Use this result": "हा निकाल वापरा",
  Retake: "पुन्हा फोटो घ्या",
  "Transparent market intelligence": "पारदर्शक बाजार माहिती",
  "Fair price board": "योग्य किंमत फलक",
  "Why this price?": "ही किंमत का?",
  "Local market average": "स्थानिक बाजार सरासरी",
  "Current recycler offers": "सध्याच्या रिसायकलर ऑफर",
  "Historical prices": "मागील किंमती",
  "Material condition": "साहित्याची स्थिती",
  Location: "ठिकाण",
  LOW: "कमी",
  HIGH: "जास्त",
  "Material inventory": "साहित्य साठा",
  "My lots": "माझे लॉट",
  "Create lot": "लॉट तयार करा",
  ALL: "सर्व",
  ACTIVE: "सक्रिय",
  PAID: "पैसे दिले",
  RECYCLED: "पुनर्वापर पूर्ण",
  Created: "तयार केले",
  "7-step guided workflow": "७ टप्प्यांची मार्गदर्शित प्रक्रिया",
  Material: "साहित्य",
  "Photo (optional offline-safe)": "फोटो (ऑफलाइन सुरक्षित, ऐच्छिक)",
  "Approximate weight (kg)": "अंदाजे वजन (किलो)",
  "Collection location": "संकलन ठिकाण",
  "Fair price estimate": "योग्य किंमत अंदाज",
  Recommended: "शिफारस केलेली किंमत",
  "Historical trend": "मागील किंमत कल",
  "Digital material record": "डिजिटल साहित्य नोंद",
  "Fair range": "योग्य किंमत श्रेणी",
  "E-waste passport": "ई-कचरा पासपोर्ट",
  "Public-safe passport": "सार्वजनिक-सुरक्षित पासपोर्ट",
  "View traceability": "ट्रेसिबिलिटी पहा",
  "Compare recyclers": "रिसायकलरची तुलना करा",
  "Explainable matching": "स्पष्ट जुळणी प्रणाली",
  "Find a trusted recycler": "विश्वसनीय रिसायकलर शोधा",
  "BEST MATCH": "सर्वोत्तम जुळणी",
  "Pickup available": "पिकअप उपलब्ध",
  "Drop-off only": "फक्त स्वतः पोहोचवा",
  "Recommended because": "शिफारसीची कारणे",
  "Get quote": "ऑफर मागवा",
  "Collector financial passport": "संकलक आर्थिक पासपोर्ट",
  "My earnings": "माझी कमाई",
  "Print statement": "विवरणपत्र छापा",
  "Total paid": "एकूण दिलेली रक्कम",
  Transactions: "व्यवहार",
  Pending: "प्रलंबित",
  "Average lot": "सरासरी लॉट",
  "Payment ledger": "पेमेंट नोंदवही",
  Method: "पद्धत",
  Date: "दिनांक",
  Amount: "रक्कम",
  Status: "स्थिती",
  "Earnings trend": "कमाईचा कल",
  "Short · Visual · Voice-ready": "लहान · दृश्य · आवाजासाठी तयार",
  "Safety centre": "सुरक्षा केंद्र",
  "Lithium battery": "लिथियम बॅटरी",
  "Displays & CRT": "डिस्प्ले आणि CRT",
  "Burning & chemicals": "जाळणे आणि रसायने",
  "Personal protection": "वैयक्तिक संरक्षण",
  "Electrical hazards": "विद्युत धोके",
  "Safe routing": "सुरक्षित पाठवणी",
  Listen: "ऐका",
  "Recycler operations": "रिसायकलर कामकाज",
  "Supply command centre": "पुरवठा नियंत्रण केंद्र",
  "Pending action": "प्रलंबित कृती",
  "Completed payments": "पूर्ण पेमेंट",
  "Transaction volume": "व्यवहार मूल्य",
  "Incoming material": "येणारे साहित्य",
  "Pickup pooling": "एकत्रित पिकअप",
  "Plan combined pickup": "एकत्रित पिकअप आखा",
  "Compatible supply": "सुसंगत पुरवठा",
  "Your offer / kg": "तुमची ऑफर / किलो",
  "Submit quote": "ऑफर पाठवा",
  "Operations desk": "कामकाज केंद्र",
  "Final weight": "अंतिम वजन",
  "Handover OTP": "हस्तांतरण OTP",
  "Confirm handover": "हस्तांतरण निश्चित करा",
  "Record simulated payment": "डेमो पेमेंट नोंदवा",
  "Weight discrepancy": "वजनातील फरक",
  "Network intelligence": "नेटवर्क माहिती",
  "Material routed": "पाठवलेले साहित्य",
  "Network GMV": "नेटवर्क GMV",
  "Risk flags": "जोखीम सूचना",
  "Material flow": "साहित्य प्रवाह",
  Collectors: "संकलक",
  "Authorized recyclers": "अधिकृत रिसायकलर",
  Processing: "प्रक्रिया",
  "Recovered materials": "पुनर्प्राप्त साहित्य",
  "Recycler network": "रिसायकलर नेटवर्क",
  Materials: "साहित्य",
  Trust: "विश्वास",
  Action: "कृती",
  "Demo verify": "डेमो पडताळणी",
  "Anomaly review": "विसंगती पुनरावलोकन",
  "REVIEW RECOMMENDED": "पुनरावलोकनाची शिफारस",
  "Dataset health": "डेटासेट स्थिती",
  Dataset: "डेटासेट",
  Records: "नोंदी",
  Updated: "अद्ययावत",
  Validation: "पडताळणी",
  Missing: "गहाळ",
  Duplicates: "डुप्लिकेट",
  Today: "आज",
  "The circular network flywheel": "परिपत्रक नेटवर्क चक्र",
  "Platform revenue": "प्लॅटफॉर्म महसूल",
  Subscriptions: "सदस्यता",
  "Contribution margin": "योगदान मार्जिन",
  "Network effect": "नेटवर्क परिणाम",
  "Platform moat": "प्लॅटफॉर्मची ताकद",
  "Revenue architecture": "महसूल रचना",
  Roadmap: "विकास आराखडा",
  Time: "वेळ",
  Actor: "कर्ता",
  Entity: "घटक",
  "Public-safe e-waste passport": "सार्वजनिक-सुरक्षित ई-कचरा पासपोर्ट",
  "Collection date": "संकलन दिनांक",
  Recycler: "रिसायकलर",
  Handover: "हस्तांतरण",
  Payment: "पेमेंट",
  Recycling: "पुनर्वापर",
  Verified: "सत्यापित",
  Completed: "पूर्ण",
  "In progress": "प्रक्रियेत",
  "Operational analytics": "कामकाज विश्लेषण",
  "Recycler performance": "रिसायकलर कामगिरी",
  "Pickup performance": "पिकअप कामगिरी",
  "On-time completion": "वेळेत पूर्ण",
  "Loading KABADI+ data…": "KABADI+ माहिती लोड होत आहे…",
  "Unable to load data.": "माहिती लोड करता आली नाही.",
  "Network active": "नेटवर्क सुरू",
  "Battery ko na jalayein": "बॅटरी जाळू नका",
  "Never puncture, burn or open a lithium battery.":
    "लिथियम बॅटरीला छिद्र पाडू नका, जाळू नका किंवा उघडू नका.",
  "Image stays local in this prototype.":
    "या प्रोटोटाइपमध्ये फोटो उपकरणावरच राहतो.",
  "Classification is deterministic from the file name in demo mode.":
    "डेमो मोडमध्ये फाइलच्या नावावरून वर्गीकरण केले जाते.",
  "Experimental/demo classification. Verify before commercial decisions.":
    "हे प्रायोगिक वर्गीकरण आहे. व्यावसायिक निर्णयापूर्वी पडताळणी करा.",
  "No collector identity or exact address is exposed.":
    "संकलकाची ओळख किंवा अचूक पत्ता दाखवला जात नाही.",
  "Verification shown here is simulated for the prototype and is not government certification.":
    "येथील पडताळणी फक्त प्रोटोटाइपसाठी आहे; हे सरकारी प्रमाणपत्र नाही.",
  "Do not puncture, burn or open. Keep away from heat.":
    "छिद्र पाडू नका, जाळू नका किंवा उघडू नका. उष्णतेपासून दूर ठेवा.",
  "Do not break glass. Avoid powder and damaged edges.":
    "काच फोडू नका. पावडर आणि तुटलेल्या कडांपासून सावध रहा.",
  "Never burn wires or electronics. Toxic fumes can cause harm.":
    "तारा किंवा इलेक्ट्रॉनिक्स जाळू नका. विषारी धूर हानिकारक असतो.",
  "Use gloves, closed shoes and eye protection.":
    "हातमोजे, बंद बूट आणि डोळ्यांचे संरक्षण वापरा.",
  "Disconnect power before handling equipment.":
    "उपकरण हाताळण्यापूर्वी वीज बंद करा.",
  "Send hazardous e-waste to an authorized recycler.":
    "धोकादायक ई-कचरा अधिकृत रिसायकलरकडे पाठवा.",
  PCB: "पीसीबी",
  Cable: "केबल",
  Battery: "बॅटरी",
  "LCD/Display": "एलसीडी/डिस्प्ले",
  CRT: "सीआरटी",
  Motor: "मोटर",
  "Mixed Plastic": "मिश्र प्लास्टिक",
  Aluminium: "ॲल्युमिनियम",
  Copper: "तांबे",
  Computer: "संगणक",
  Laptop: "लॅपटॉप",
  "Mobile Phone": "मोबाइल फोन",
  "Other E-Waste": "इतर ई-कचरा",
  "/kg": "/किलो",
  " kg": " किलो",
  "बैटरी को न खोलें": "बॅटरी उघडू नका",
  "स्क्रीन सावधानी से रखें": "स्क्रीन काळजीपूर्वक ठेवा",
  "कचरा न जलाएं": "कचरा जाळू नका",
  "दस्ताने पहनें": "हातमोजे घाला",
  "बिजली काट दें": "वीज बंद करा",
  "सही रिसायकलर चुनें": "योग्य रिसायकलर निवडा",
};
const hi: Record<string, string> = {
  Home: "होम",
  Lots: "लॉट",
  Prices: "कीमतें",
  Recyclers: "रीसाइक्लर",
  Safety: "सुरक्षा",
  Earnings: "कमाई",
  Dashboard: "डैशबोर्ड",
  "Incoming lots": "आने वाले लॉट",
  Operations: "संचालन",
  Analytics: "विश्लेषण",
  Intelligence: "नेटवर्क जानकारी",
  Anomalies: "असामान्यताएँ",
  Datasets: "डेटासेट",
  Business: "व्यवसाय",
  "Audit log": "ऑडिट लॉग",
  "DEMO MODE": "डेमो मोड",
  "SMART E-WASTE NETWORK": "स्मार्ट ई-कचरा नेटवर्क",
  "COLLECTOR workspace": "संग्रहकर्ता कार्यक्षेत्र",
  "RECYCLER workspace": "रीसाइक्लर कार्यक्षेत्र",
  "ADMIN workspace": "प्रशासक कार्यक्षेत्र",
  "Collector home": "संग्रहकर्ता होम",
  Namaste: "नमस्ते",
  "Network active": "नेटवर्क सक्रिय",
  "This month": "इस महीने",
  "Formal e-waste": "औपचारिक ई-कचरा",
  "Safely routed": "सुरक्षित रूप से भेजा",
  "Active lots": "सक्रिय लॉट",
  "Across the network": "पूरे नेटवर्क में",
  "Trusted recyclers": "विश्वसनीय रीसाइक्लर",
  "Demo-verified": "डेमो-सत्यापित",
  "What do you want to do?": "आप क्या करना चाहते हैं?",
  "Why KABADI+?": "KABADI+ क्यों?",
  "Safety reminder": "सुरक्षा सूचना",
  "Open safety centre": "सुरक्षा केंद्र खोलें",
  "Scan Scrap": "स्क्रैप स्कैन करें",
  "Check Prices": "कीमत देखें",
  "Find Recycler": "रीसाइक्लर खोजें",
  "My Lots": "मेरे लॉट",
  "My Earnings": "मेरी कमाई",
  "Fair price": "उचित कीमत",
  "Trusted recycler": "विश्वसनीय रीसाइक्लर",
  "Verified handover": "सत्यापित हस्तांतरण",
  Payment: "भुगतान",
  Traceability: "ट्रेसबिलिटी",
  "AI-assisted identification": "AI-सहायता से पहचान",
  "Scan scrap": "स्क्रैप स्कैन करें",
  "AI DEMO MODEL": "AI डेमो मॉडल",
  "Take or choose a scrap photo": "स्क्रैप की फोटो लें या चुनें",
  "Open camera": "कैमरा खोलें",
  "Analyze material": "सामग्री जाँचें",
  "AI result will appear here": "AI परिणाम यहाँ दिखेगा",
  "AI result": "AI परिणाम",
  Confidence: "विश्वास स्तर",
  Condition: "स्थिति",
  "Estimated weight": "अनुमानित वजन",
  "Estimated fair value": "अनुमानित उचित मूल्य",
  "Use this result": "यह परिणाम उपयोग करें",
  Retake: "फिर से फोटो लें",
  "Transparent market intelligence": "पारदर्शी बाजार जानकारी",
  "Fair price board": "उचित कीमत बोर्ड",
  "Why this price?": "यह कीमत क्यों?",
  "Local market average": "स्थानीय बाजार औसत",
  "Current recycler offers": "मौजूदा रीसाइक्लर ऑफर",
  "Historical prices": "पिछली कीमतें",
  "Material condition": "सामग्री की स्थिति",
  Location: "स्थान",
  LOW: "कम",
  HIGH: "अधिक",
  "Material inventory": "सामग्री सूची",
  "My lots": "मेरे लॉट",
  "Create lot": "लॉट बनाएँ",
  ALL: "सभी",
  ACTIVE: "सक्रिय",
  PAID: "भुगतान हुआ",
  RECYCLED: "रीसाइक्लिंग पूरी",
  Created: "बनाया गया",
  Material: "सामग्री",
  "Approximate weight (kg)": "अनुमानित वजन (किलो)",
  "Collection location": "संग्रह स्थान",
  "Fair price estimate": "उचित कीमत अनुमान",
  Recommended: "अनुशंसित",
  "Historical trend": "पिछला रुझान",
  "Digital material record": "डिजिटल सामग्री रिकॉर्ड",
  "Fair range": "उचित कीमत सीमा",
  "E-waste passport": "ई-कचरा पासपोर्ट",
  "Public-safe passport": "सार्वजनिक-सुरक्षित पासपोर्ट",
  "View traceability": "ट्रेसबिलिटी देखें",
  "Compare recyclers": "रीसाइक्लर की तुलना करें",
  "Explainable matching": "स्पष्ट मिलान प्रणाली",
  "Find a trusted recycler": "विश्वसनीय रीसाइक्लर खोजें",
  "BEST MATCH": "सर्वोत्तम मिलान",
  "Pickup available": "पिकअप उपलब्ध",
  "Drop-off only": "केवल स्वयं पहुँचाएँ",
  "Recommended because": "अनुशंसा के कारण",
  "Get quote": "ऑफर माँगें",
  "Collector financial passport": "संग्रहकर्ता वित्तीय पासपोर्ट",
  "Print statement": "विवरण प्रिंट करें",
  "Total paid": "कुल भुगतान",
  Transactions: "लेनदेन",
  Pending: "लंबित",
  "Average lot": "औसत लॉट",
  "Payment ledger": "भुगतान खाता",
  Method: "तरीका",
  Date: "तारीख",
  Amount: "राशि",
  Status: "स्थिति",
  "Earnings trend": "कमाई का रुझान",
  "Safety centre": "सुरक्षा केंद्र",
  "Lithium battery": "लिथियम बैटरी",
  "Displays & CRT": "डिस्प्ले और CRT",
  "Burning & chemicals": "जलाना और रसायन",
  "Personal protection": "व्यक्तिगत सुरक्षा",
  "Electrical hazards": "बिजली के खतरे",
  "Safe routing": "सुरक्षित भेजना",
  Listen: "सुनें",
  "Recycler operations": "रीसाइक्लर संचालन",
  "Supply command centre": "आपूर्ति नियंत्रण केंद्र",
  "Pending action": "लंबित कार्रवाई",
  "Completed payments": "पूर्ण भुगतान",
  "Transaction volume": "लेनदेन मूल्य",
  "Incoming material": "आने वाली सामग्री",
  "Pickup pooling": "संयुक्त पिकअप",
  "Plan combined pickup": "संयुक्त पिकअप बनाएँ",
  "Compatible supply": "अनुकूल आपूर्ति",
  "Your offer / kg": "आपका ऑफर / किलो",
  "Submit quote": "ऑफर भेजें",
  "Operations desk": "संचालन केंद्र",
  "Final weight": "अंतिम वजन",
  "Handover OTP": "हस्तांतरण OTP",
  "Confirm handover": "हस्तांतरण की पुष्टि करें",
  "Record simulated payment": "डेमो भुगतान दर्ज करें",
  "Weight discrepancy": "वजन में अंतर",
  "Network intelligence": "नेटवर्क जानकारी",
  "Material routed": "भेजी गई सामग्री",
  "Network GMV": "नेटवर्क GMV",
  "Risk flags": "जोखिम चेतावनी",
  "Material flow": "सामग्री प्रवाह",
  Collectors: "संग्रहकर्ता",
  "Authorized recyclers": "अधिकृत रीसाइक्लर",
  Processing: "प्रसंस्करण",
  "Recovered materials": "पुनर्प्राप्त सामग्री",
  "Recycler network": "रीसाइक्लर नेटवर्क",
  Materials: "सामग्री",
  Trust: "विश्वास",
  Action: "कार्रवाई",
  "Demo verify": "डेमो सत्यापन",
  "Anomaly review": "असामान्यता समीक्षा",
  "REVIEW RECOMMENDED": "समीक्षा की सलाह",
  "Dataset health": "डेटासेट स्थिति",
  Dataset: "डेटासेट",
  Records: "रिकॉर्ड",
  Updated: "अपडेट",
  Validation: "सत्यापन",
  Missing: "अनुपलब्ध",
  Duplicates: "डुप्लिकेट",
  Today: "आज",
  "Platform revenue": "प्लेटफॉर्म आय",
  Subscriptions: "सदस्यता",
  "Contribution margin": "योगदान मार्जिन",
  "Network effect": "नेटवर्क प्रभाव",
  "Platform moat": "प्लेटफॉर्म की ताकत",
  "Revenue architecture": "आय संरचना",
  Roadmap: "विकास योजना",
  Time: "समय",
  Actor: "कर्ता",
  Entity: "इकाई",
  "Public-safe e-waste passport": "सार्वजनिक-सुरक्षित ई-कचरा पासपोर्ट",
  "Collection date": "संग्रह तारीख",
  Recycler: "रीसाइक्लर",
  Handover: "हस्तांतरण",
  Recycling: "रीसाइक्लिंग",
  Verified: "सत्यापित",
  Completed: "पूर्ण",
  "In progress": "प्रगति पर",
  "Operational analytics": "संचालन विश्लेषण",
  "Recycler performance": "रीसाइक्लर प्रदर्शन",
  "Pickup performance": "पिकअप प्रदर्शन",
  "On-time completion": "समय पर पूर्ण",
  PCB: "पीसीबी",
  Cable: "केबल",
  Battery: "बैटरी",
  "LCD/Display": "एलसीडी/डिस्प्ले",
  CRT: "सीआरटी",
  Motor: "मोटर",
  "Mixed Plastic": "मिश्रित प्लास्टिक",
  Aluminium: "एल्युमिनियम",
  Copper: "ताँबा",
  Computer: "कंप्यूटर",
  Laptop: "लैपटॉप",
  "Mobile Phone": "मोबाइल फोन",
  "Other E-Waste": "अन्य ई-कचरा",
  "/kg": "/किलो",
  " kg": " किलो",
};

Object.assign(mr, {
  workspace: "कार्यक्षेत्र",
  "Fair price": "योग्य किंमत",
  "Trusted recycler": "विश्वसनीय रिसायकलर",
  "Verified handover": "सत्यापित हस्तांतरण",
  Traceability: "ट्रेसिबिलिटी",
  Payment: "पेमेंट",
  "Safety reminder": "सुरक्षा सूचना",
});
Object.assign(hi, {
  workspace: "कार्यक्षेत्र",
  "vs last month": "पिछले महीने की तुलना में",
  "Battery ko na jalayein": "बैटरी न जलाएँ",
  "Never puncture, burn or open a lithium battery.":
    "लिथियम बैटरी में छेद न करें, उसे जलाएँ या खोलें नहीं।",
  "Image stays local in this prototype.":
    "इस प्रोटोटाइप में फोटो आपके उपकरण पर ही रहती है।",
  "Classification is deterministic from the file name in demo mode.":
    "डेमो मोड में फाइल नाम से निश्चित वर्गीकरण किया जाता है।",
  "Experimental/demo classification. Verify before commercial decisions.":
    "यह प्रायोगिक डेमो वर्गीकरण है। व्यावसायिक निर्णय से पहले जाँच करें।",
  "No collector identity or exact address is exposed.":
    "संग्रहकर्ता की पहचान या सटीक पता नहीं दिखाया जाता।",
  "Verification shown here is simulated for the prototype and is not government certification.":
    "यह सत्यापन केवल प्रोटोटाइप के लिए है; यह सरकारी प्रमाणपत्र नहीं है।",
  "Do not puncture, burn or open. Keep away from heat.":
    "छेद न करें, जलाएँ या खोलें नहीं। गर्मी से दूर रखें।",
  "Do not break glass. Avoid powder and damaged edges.":
    "काँच न तोड़ें। पाउडर और टूटी किनारियों से बचें।",
  "Never burn wires or electronics. Toxic fumes can cause harm.":
    "तार या इलेक्ट्रॉनिक्स न जलाएँ। जहरीला धुआँ हानिकारक है।",
  "Use gloves, closed shoes and eye protection.":
    "दस्ताने, बंद जूते और आँखों की सुरक्षा पहनें।",
  "Disconnect power before handling equipment.":
    "उपकरण संभालने से पहले बिजली बंद करें।",
  "Send hazardous e-waste to an authorized recycler.":
    "खतरनाक ई-कचरा अधिकृत रीसाइक्लर को भेजें।",
});

Object.assign(mr, {
  COLLECTOR: "संकलक",
  RECYCLER: "रिसायकलर",
  ADMIN: "प्रशासक",
  "vs last month": "मागील महिन्याच्या तुलनेत",
});
Object.assign(hi, {
  COLLECTOR: "संग्रहकर्ता",
  RECYCLER: "रीसाइक्लर",
  ADMIN: "प्रशासक",
});
Object.assign(mr, {
  "Do not burn batteries": "बॅटरी जाळू नका",
  "Formalization intelligence · Demo analytics":
    "औपचारिकीकरण माहिती · डेमो विश्लेषण",
});
Object.assign(hi, {
  "Do not burn batteries": "बैटरी न जलाएँ",
  "7-step guided workflow": "7 चरणों की मार्गदर्शित प्रक्रिया",
  "Short · Visual · Voice-ready": "छोटा · दृश्य · आवाज के लिए तैयार",
  "Formalization intelligence · Demo analytics":
    "औपचारिकीकरण जानकारी · डेमो विश्लेषण",
});
Object.assign(mr, {
  "Create a lot": "लॉट तयार करा",
  "Photo (optional offline-safe)": "फोटो (ऑफलाइन सुरक्षित, ऐच्छिक)",
  POOR: "खराब",
  USED: "वापरलेले",
  GOOD: "चांगले",
  "Local market & current offers": "स्थानिक बाजार आणि सध्याच्या ऑफर",
  "Condition and location": "स्थिती आणि ठिकाण",
  "Authorization demo-verified": "परवानगी डेमो-पडताळलेली",
  "High compatible offer": "चांगली सुसंगत ऑफर",
  "Nearby with pickup": "जवळ आणि पिकअप उपलब्ध",
  "Strong reliability": "उच्च विश्वासार्हता",
  VERIFIED: "सत्यापित",
  km: "किमी",
  "Do not open batteries": "बॅटरी उघडू नका",
  "Handle the screen carefully": "स्क्रीन काळजीपूर्वक ठेवा",
  "Do not burn waste": "कचरा जाळू नका",
  "Wear gloves": "हातमोजे घाला",
  "Switch off electricity": "वीज बंद करा",
  "Choose the right recycler": "योग्य रिसायकलर निवडा",
  May: "मे",
  Jun: "जून",
  Jul: "जुलै",
  Aug: "ऑगस्ट",
  Sep: "सप्टेंबर",
  "3 nearby PCB lots in Pune East can be combined.":
    "पुणे पूर्वमधील ३ जवळचे पीसीबी लॉट एकत्र उचलता येतील.",
  "Estimated 22% logistics saving": "अंदाजे २२% वाहतूक बचत",
  "FORMALIZATION INTELLIGENCE · DEMO ANALYTICS":
    "औपचारिकीकरण माहिती · डेमो विश्लेषण",
  "Informal → formal lots": "अनौपचारिक → औपचारिक लॉट",
  Aggregators: "संकलक केंद्रे",
  "Collection density · Coarse geography": "संकलन घनता · अंदाजे भूगोल",
  "Pune network · approximate locations only":
    "पुणे नेटवर्क · फक्त अंदाजे ठिकाणे",
  "Formalization trend": "औपचारिकीकरणाचा कल",
  "SHORT · VISUAL · VOICE-READY": "लहान · दृश्य · आवाजासाठी तयार",
  "7-STEP GUIDED WORKFLOW": "७ टप्प्यांची मार्गदर्शित प्रक्रिया",
});
Object.assign(hi, {
  "Create a lot": "लॉट बनाएँ",
  "Photo (optional offline-safe)": "फोटो (ऑफलाइन सुरक्षित, वैकल्पिक)",
  POOR: "खराब",
  USED: "उपयोग किया हुआ",
  GOOD: "अच्छा",
  "Local market & current offers": "स्थानीय बाजार और मौजूदा ऑफर",
  "Condition and location": "स्थिति और स्थान",
  "Authorization demo-verified": "अनुमति डेमो-सत्यापित",
  "High compatible offer": "अच्छा अनुकूल ऑफर",
  "Nearby with pickup": "पास और पिकअप उपलब्ध",
  "Strong reliability": "उच्च विश्वसनीयता",
  VERIFIED: "सत्यापित",
  km: "किमी",
  "Do not open batteries": "बैटरी को न खोलें",
  "Handle the screen carefully": "स्क्रीन सावधानी से रखें",
  "Do not burn waste": "कचरा न जलाएँ",
  "Wear gloves": "दस्ताने पहनें",
  "Switch off electricity": "बिजली बंद करें",
  "Choose the right recycler": "सही रीसाइक्लर चुनें",
  May: "मई",
  Jun: "जून",
  Jul: "जुलाई",
  Aug: "अगस्त",
  Sep: "सितंबर",
  "3 nearby PCB lots in Pune East can be combined.":
    "पुणे पूर्व के 3 पास के पीसीबी लॉट एक साथ उठाए जा सकते हैं।",
  "Estimated 22% logistics saving": "अनुमानित 22% परिवहन बचत",
  "FORMALIZATION INTELLIGENCE · DEMO ANALYTICS":
    "औपचारिकीकरण जानकारी · डेमो विश्लेषण",
  "Informal → formal lots": "अनौपचारिक → औपचारिक लॉट",
  Aggregators: "संग्रह केंद्र",
  "Collection density · Coarse geography": "संग्रह घनत्व · अनुमानित भूगोल",
  "Pune network · approximate locations only":
    "पुणे नेटवर्क · केवल अनुमानित स्थान",
  "Formalization trend": "औपचारिकीकरण का रुझान",
  "SHORT · VISUAL · VOICE-READY": "छोटा · दृश्य · आवाज के लिए तैयार",
  "7-STEP GUIDED WORKFLOW": "7 चरणों की मार्गदर्शित प्रक्रिया",
});

Object.assign(mr,{"Scan Scrap":"स्क्रॅप स्कॅन करा","CREATED":"तयार","QUOTED":"ऑफर मिळाली","ACCEPTED":"स्वीकारले","My earnings":"माझी कमाई","LOT":"लॉट","AI estimate":"AI अंदाज","Pickup · Handover · Payment":"पिकअप · हस्तांतरण · पेमेंट","reported":"नोंदवलेले","Admin review will be created.":"प्रशासकीय पुनरावलोकन तयार केले जाईल.","this month":"या महिन्यात","Due diligence workflow":"पडताळणी प्रक्रिया","Prototype record":"प्रोटोटाइप नोंद","Fairness & integrity controls":"योग्य किंमत आणि प्रामाणिकपणा नियंत्रण","Structured network data":"रचनाबद्ध नेटवर्क डेटा","VALIDATED":"पडताळलेले","REVIEW":"पुनरावलोकन","AI image labels":"AI प्रतिमा लेबले","DEMO ONLY":"फक्त डेमो","AI dataset figures describe demo samples only. No measured production accuracy is claimed.":"AI डेटासेटची आकडेवारी फक्त डेमो नमुने दर्शवते. प्रत्यक्ष अचूकतेचा दावा केलेला नाही.","Investor view · Demo economics":"गुंतवणूकदार दृश्य · डेमो अर्थशास्त्र","More material":"अधिक साहित्य","competition":"स्पर्धा","Better prices":"चांगल्या किंमती","More adoption":"अधिक स्वीकार","More data":"अधिक डेटा","Better intelligence":"चांगली माहिती","NETWORK":"नेटवर्क","TRANSACTION DATA":"व्यवहार डेटा","PRICE HISTORY":"किंमत इतिहास","PERFORMANCE":"कामगिरी","MATERIAL INTELLIGENCE":"साहित्य माहिती","SaaS":"सास","Transaction fees":"व्यवहार शुल्क","Enterprise":"उद्योग सेवा","Logistics":"वाहतूक","Now":"आता","E-waste":"ई-कचरा","Immutable operational history":"अपरिवर्तनीय कामकाज इतिहास","Actions performed in this session will appear here.":"या सत्रात केलेल्या कृती येथे दिसतील."});
Object.assign(hi,{"CREATED":"बनाया गया","QUOTED":"ऑफर मिली","ACCEPTED":"स्वीकृत","My earnings":"मेरी कमाई","LOT":"लॉट","AI estimate":"AI अनुमान","Pickup · Handover · Payment":"पिकअप · हस्तांतरण · भुगतान","reported":"दर्ज वजन","Admin review will be created.":"प्रशासकीय समीक्षा बनाई जाएगी।","this month":"इस महीने","Due diligence workflow":"सत्यापन प्रक्रिया","Prototype record":"प्रोटोटाइप रिकॉर्ड","Fairness & integrity controls":"उचित कीमत और ईमानदारी नियंत्रण","Structured network data":"संरचित नेटवर्क डेटा","VALIDATED":"सत्यापित","REVIEW":"समीक्षा","AI image labels":"AI चित्र लेबल","DEMO ONLY":"केवल डेमो","AI dataset figures describe demo samples only. No measured production accuracy is claimed.":"AI डेटासेट के आँकड़े केवल डेमो नमूने हैं। वास्तविक सटीकता का दावा नहीं किया गया है।","Investor view · Demo economics":"निवेशक दृश्य · डेमो अर्थशास्त्र","The circular network flywheel":"परिपत्र नेटवर्क चक्र","More material":"अधिक सामग्री","competition":"प्रतिस्पर्धा","Better prices":"बेहतर कीमतें","More adoption":"अधिक अपनाना","More data":"अधिक डेटा","Better intelligence":"बेहतर जानकारी","NETWORK":"नेटवर्क","TRANSACTION DATA":"लेनदेन डेटा","PRICE HISTORY":"कीमत इतिहास","PERFORMANCE":"प्रदर्शन","MATERIAL INTELLIGENCE":"सामग्री जानकारी","SaaS":"सास","Transaction fees":"लेनदेन शुल्क","Enterprise":"उद्यम सेवा","Logistics":"परिवहन","Now":"अभी","E-waste":"ई-कचरा","Immutable operational history":"अपरिवर्तनीय संचालन इतिहास","Actions performed in this session will appear here.":"इस सत्र में की गई कार्रवाइयाँ यहाँ दिखाई देंगी।"});

Object.assign(hi, {
  "Scrap collection.": "कबाड़ संग्रह।",
  "Now simple and smart.": "अब सरल और स्मार्ट।",
  "Take a photo, check the fair price, and sell to a verified recycler.": "फोटो लें, उचित कीमत देखें और सत्यापित रीसाइक्लर को बेचें।",
  "One simple promise": "एक सरल वादा",
  "Fair price · Accurate weight": "उचित कीमत · सही वजन",
  "Secure payment": "सुरक्षित भुगतान",
  "Want to sell scrap?": "क्या आप कबाड़ बेचना चाहते हैं?",
  "Take a photo. We will identify the material, estimate its value, and find a nearby verified buyer.": "फोटो लें। हम सामग्री पहचानेंगे, उसका मूल्य बताएँगे और पास का सत्यापित खरीदार खोजेंगे।",
  "Start with a photo": "फोटो से शुरू करें",
  "Add without a photo": "बिना फोटो के जोड़ें",
  "Quick actions": "त्वरित कार्य",
  "What would you like to do?": "आप क्या करना चाहते हैं?",
  "Large buttons · fewer steps": "बड़े बटन · कम चरण",
  "The CHAKRASETU trust cycle": "CHAKRASETU विश्वास चक्र",
  "Verified Weight": "सत्यापित वजन",
  "Lock the digital weight after OTP verification": "OTP सत्यापन के बाद डिजिटल वजन लॉक करें",
  "Smart Pickup Routes": "स्मार्ट पिकअप मार्ग",
  "Combine nearby pickups to save time and fuel": "समय और ईंधन बचाने के लिए पास के पिकअप जोड़ें",
  "Price Alerts": "कीमत अलर्ट",
  "Get an alert when your local scrap rate increases": "स्थानीय कबाड़ दर बढ़ने पर अलर्ट पाएँ",
  "Find the right recycler nearby": "पास का सही रीसाइक्लर खोजें",
  "Request pickup quote": "पिकअप ऑफर माँगें",
  "Loading CHAKRASETU data…": "CHAKRASETU डेटा लोड हो रहा है…"
});
Object.assign(mr, {
  "Scrap collection.": "भंगार संकलन.",
  "Now simple and smart.": "आता सोपे आणि स्मार्ट.",
  "Take a photo, check the fair price, and sell to a verified recycler.": "फोटो घ्या, योग्य किंमत पहा आणि सत्यापित रिसायकलरला विका.",
  "One simple promise": "एक सोपे वचन",
  "Fair price · Accurate weight": "योग्य किंमत · अचूक वजन",
  "Secure payment": "सुरक्षित पेमेंट",
  "Want to sell scrap?": "भंगार विकायचे आहे?",
  "Take a photo. We will identify the material, estimate its value, and find a nearby verified buyer.": "फोटो घ्या. आम्ही साहित्य ओळखू, किंमतीचा अंदाज देऊ आणि जवळचा सत्यापित खरेदीदार शोधू.",
  "Start with a photo": "फोटोने सुरुवात करा",
  "Add without a photo": "फोटोशिवाय जोडा",
  "Quick actions": "जलद कृती",
  "What would you like to do?": "तुम्हाला काय करायचे आहे?",
  "Large buttons · fewer steps": "मोठी बटणे · कमी टप्पे",
  "The CHAKRASETU trust cycle": "CHAKRASETU विश्वास चक्र",
  "Verified Weight": "सत्यापित वजन",
  "Lock the digital weight after OTP verification": "OTP पडताळणीनंतर डिजिटल वजन लॉक करा",
  "Smart Pickup Routes": "स्मार्ट पिकअप मार्ग",
  "Combine nearby pickups to save time and fuel": "वेळ आणि इंधन वाचवण्यासाठी जवळचे पिकअप एकत्र करा",
  "Price Alerts": "किंमत सूचना",
  "Get an alert when your local scrap rate increases": "स्थानिक भंगार दर वाढल्यावर सूचना मिळवा",
  "Find the right recycler nearby": "जवळचा योग्य रिसायकलर शोधा",
  "Request pickup quote": "पिकअप ऑफर मागवा",
  "Loading CHAKRASETU data…": "CHAKRASETU माहिती लोड होत आहे…"
});

let busy = false;
const tables = { hi, mr };
const reverse = Object.entries(tables)
  .flatMap(([, table]) => Object.entries(table))
  .sort((a, b) => b[1].length - a[1].length);
const canonical = (text: string) => {
  let out = text;
  for (const [en, localized] of reverse) out = out.replaceAll(localized, en);
  return out;
};
const replaceEnglish = (text: string, english: string, value: string) => {
  if (!/^[A-Za-z ]+$/.test(english)) return text.replaceAll(english, value);
  const escaped = english.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return text.replace(new RegExp(`\\b${escaped}\\b`, "g"), value);
};
function applyLanguage() {
  if (busy || !document.body) return;
  busy = true;
  const lang =
    i18n.language === "mr" ? "mr" : i18n.language === "hi" ? "hi" : "en";
  const table = lang === "en" ? null : tables[lang];
  const entries = table
    ? Object.entries(table).sort((a, b) => b[0].length - a[0].length)
    : [];
  const w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let n: Node | null;
  while ((n = w.nextNode())) {
    const t = n as Text;
    let out = canonical(t.data);
    for (const [en, value] of entries) out = replaceEnglish(out, en, value);
    if (lang === "mr")
      out = out
        .replaceAll("बॅटरी को न खोलें", "बॅटरी उघडू नका")
        .replaceAll("सही रिसायकलर चुनें", "योग्य रिसायकलर निवडा")
        .replace(/\bkg\b/g, "किलो");
    if (lang === "hi") out = out.replace(/\bkg\b/g, "किलो");
    if (t.data !== out) t.data = out;
  }
  document
    .querySelectorAll<HTMLInputElement>("input[placeholder]")
    .forEach((e) => {
      const base = canonical(e.dataset.en || e.placeholder);
      e.dataset.en = base;
      e.placeholder =
        lang === "mr"
          ? base
              .replace("Search material", "साहित्य शोधा")
              .replace(
                "Search PCB, cable, battery…",
                "पीसीबी, केबल, बॅटरी शोधा…",
              )
          : lang === "hi"
            ? base
                .replace("Search material", "सामग्री खोजें")
                .replace(
                  "Search PCB, cable, battery…",
                  "पीसीबी, केबल, बैटरी खोजें…",
                )
            : base;
    });
  busy = false;
}
const observer = new MutationObserver(() => queueMicrotask(applyLanguage));
window.addEventListener("DOMContentLoaded", () => {
  observer.observe(document.body, { childList: true, subtree: true });
  applyLanguage();
});
i18n.on("languageChanged", () => queueMicrotask(applyLanguage));
