import {useRef,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {useTranslation} from "react-i18next";
import i18n from "./i18n";
import {api,session} from "./api";
import "./order-chat.css";
import "./demo-recycler-preview.css";
import "./demo-recycler-selection.css";
import {demoEnabled} from "./demo-config";
const copy={en:{chat:"Order chat",empty:"No messages yet. Ask about your pickup here.",placeholder:"Write a message…",send:"Send",sending:"Sending…",loading:"Loading messages…",retry:"Retry",error:"Unable to load messages",demo:"Add demo recyclers for this pincode",demoNote:"Local prototype only. Sample prices, not real businesses. Recycler login: 9000000001 / 9000000002 / 9000000003; OTP: 123456. No automatic replies.",offline:"You are offline. Reconnect to send your message."},hi:{chat:"ऑर्डर चैट",empty:"अभी कोई संदेश नहीं। यहाँ पिकअप के बारे में पूछें।",placeholder:"संदेश लिखें…",send:"भेजें",sending:"भेज रहे हैं…",loading:"संदेश लोड हो रहे हैं…",retry:"फिर कोशिश करें",error:"संदेश लोड नहीं हुए",demo:"इस पिनकोड के लिए डेमो रीसाइक्लर जोड़ें",demoNote:"केवल स्थानीय प्रोटोटाइप। नमूना दरें, वास्तविक व्यवसाय नहीं। रीसाइक्लर लॉगिन: 9000000001 / 9000000002 / 9000000003; OTP: 123456। स्वचालित जवाब नहीं।",offline:"आप ऑफलाइन हैं। संदेश भेजने के लिए इंटरनेट से जुड़ें।"},mr:{chat:"ऑर्डर चॅट",empty:"अद्याप संदेश नाहीत. येथे पिकअपबद्दल विचारा.",placeholder:"संदेश लिहा…",send:"पाठवा",sending:"पाठवत आहे…",loading:"संदेश लोड होत आहेत…",retry:"पुन्हा प्रयत्न करा",error:"संदेश लोड झाले नाहीत",demo:"या पिनकोडसाठी डेमो रिसायकलर जोडा",demoNote:"फक्त स्थानिक प्रोटोटाइप. नमुना दर, खरे व्यवसाय नाहीत. रिसायकलर लॉगिन: 9000000001 / 9000000002 / 9000000003; OTP: 123456. स्वयंचलित प्रतिसाद नाहीत.",offline:"तुम्ही ऑफलाइन आहात. संदेश पाठवण्यासाठी इंटरनेटशी कनेक्ट करा."}};
Object.entries(copy).forEach(([lang,values])=>i18n.addResourceBundle(lang,"orderChat",values,true,true));
Object.entries({en:{buyers:"Choose your recycler",preview:"Demo preview",ready:"Add an item to your cart and enter a six-digit pincode to see prices and select a recycler."},hi:{buyers:"अपना रीसाइक्लर चुनें",preview:"डेमो पूर्वावलोकन",ready:"दरें देखने और रीसाइक्लर चुनने के लिए कार्ट में सामान जोड़ें और छह अंकों का पिनकोड भरें।"},mr:{buyers:"तुमचा रिसायकलर निवडा",preview:"डेमो पूर्वावलोकन",ready:"दर पाहण्यासाठी आणि रिसायकलर निवडण्यासाठी कार्टमध्ये वस्तू जोडा आणि सहा अंकी पिनकोड भरा."}}).forEach(([lang,values])=>i18n.addResourceBundle(lang,"orderChat",values,true,true));
Object.entries({en:{chosen:"Selected · Demo",ready:"Select a demo recycler now. Add an item to your cart and enter a six-digit pincode to load its price and place your order."},hi:{chosen:"चयनित · डेमो",ready:"अभी डेमो रीसाइक्लर चुनें। कीमत देखने और ऑर्डर देने के लिए कार्ट में सामान और छह अंकों का पिनकोड जोड़ें।"},mr:{chosen:"निवडलेले · डेमो",ready:"आता डेमो रिसायकलर निवडा. दर पाहण्यासाठी आणि ऑर्डर देण्यासाठी कार्टमध्ये वस्तू आणि सहा अंकी पिनकोड जोडा."}}).forEach(([lang,values])=>i18n.addResourceBundle(lang,"orderChat",values,true,true));
export function DemoBuyers({selectedId,onSelect}:{selectedId:string;onSelect:(id:string)=>void}){
 const {t}=useTranslation("orderChat");
 if(!demoEnabled)return null;
 return <section className="demo-recycler-preview"><h3>{t("buyers")}</h3><div className="demo-recycler-list">{["RenewHub Demo","EcoCollect Demo","GreenLoop Demo"].map((name,index)=>{const id=`demo-buyer-${3-index}`;return <button type="button" aria-pressed={selectedId===id} className={`demo-recycler-card ${selectedId===id?"selected":""}`} key={id} onClick={()=>onSelect(id)}><span className="demo-recycler-avatar" aria-hidden="true">♻</span><span><span className="badge">{t(selectedId===id?"chosen":"preview")}</span><strong className="demo-recycler-name">{name}</strong></span>{selectedId===id&&<span aria-hidden="true">✓</span>}</button>})}</div><p className="muted">{t("ready")}</p></section>;
}
Object.entries({en:{assignedOrders:"Orders selected for you",ordersLoading:"Loading pickup orders…",ordersError:"Unable to load orders.",ordersEmpty:"No pickup orders yet.",sampleOrder:"Demo order · sample customer and address"},hi:{assignedOrders:"आपके लिए चुने गए ऑर्डर",ordersLoading:"पिकअप ऑर्डर लोड हो रहे हैं…",ordersError:"ऑर्डर लोड नहीं हुए।",ordersEmpty:"अभी कोई पिकअप ऑर्डर नहीं है।",sampleOrder:"डेमो ऑर्डर · नमूना ग्राहक और पता"},mr:{assignedOrders:"तुमच्यासाठी निवडलेल्या ऑर्डर",ordersLoading:"पिकअप ऑर्डर लोड होत आहेत…",ordersError:"ऑर्डर लोड झाल्या नाहीत.",ordersEmpty:"अद्याप पिकअप ऑर्डर नाहीत.",sampleOrder:"डेमो ऑर्डर · नमुना ग्राहक आणि पत्ता"}}).forEach(([lang,values])=>i18n.addResourceBundle(lang,"orderChat",values,true,true));
export default function OrderChat({orderId}:{orderId:string}){
 const {t}=useTranslation("orderChat");const [open,setOpen]=useState(false),[text,setText]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const pending=useRef<{text:string;clientId:string}|null>(null);
 const q=useQuery({queryKey:["order-chat",session.user?.id,orderId],queryFn:()=>api<any[]>(`/marketplace/orders/${orderId}/messages`),enabled:open,refetchInterval:open?3000:false});
 const send=async(e:React.FormEvent)=>{e.preventDefault();if(busy||!text.trim())return;if(!navigator.onLine){setError(t("offline"));return;}setBusy(true);setError("");if(pending.current?.text!==text.trim())pending.current={text:text.trim(),clientId:crypto.randomUUID()};try{await api(`/marketplace/orders/${orderId}/messages`,{method:"POST",body:JSON.stringify(pending.current)});setText("");pending.current=null;await q.refetch();}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <section className="order-chat"><button className="btn outline full" aria-expanded={open} onClick={()=>setOpen(!open)}>{t("chat")} {open?"−":"+"}</button>{open&&<><div className="chat-messages" role="log" aria-live="polite">{q.isLoading&&<p>{t("loading")}</p>}{q.error&&<p role="alert">{t("error")} <button onClick={()=>q.refetch()}>{t("retry")}</button></p>}{q.data?.length===0&&<p className="muted">{t("empty")}</p>}{q.data?.map(m=><div key={m.id} className={`chat-bubble ${m.senderId===session.user?.id?"mine":""}`}><b>{m.senderName}</b><p>{m.text}</p><small>{new Date(m.createdAt).toLocaleString()}</small></div>)}</div><form onSubmit={send}><textarea aria-label={t("placeholder")} placeholder={t("placeholder")} value={text} maxLength={1000} disabled={busy} onChange={e=>setText(e.target.value)}/><button className="btn" disabled={busy||!text.trim()}>{t(busy?"sending":"send")}</button></form>{error&&<p role="alert" className="notice">{error}</p>}</>}</section>;
}
